name: habits_tracker
description: Doubletapp internship task.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Main architecture
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  equatable: ^2.0.5

  # Web components
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1

  # Local data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Widgets, components and icons
  flutter_spinkit: ^5.2.0

  # Utilities
  intl: ^0.18.1

  # Initial dependencies
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
